using Erp.Core.Interfaces;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace Erp.Infrastructure.Storage;

/// <summary>
/// Attachments on the API server's own filesystem. Fits a single-server, single-tenant
/// deployment and costs nothing to run; the trade is that the folder has to outlive a redeploy
/// and does not span multiple API instances. Point <see cref="LeaveAttachmentOptions.RootPath"/>
/// at persistent storage, or swap in an object-storage implementation, if either becomes true.
/// </summary>
public sealed class LocalLeaveAttachmentStorage : ILeaveAttachmentStorage
{
    private readonly string _root;
    private readonly ILogger<LocalLeaveAttachmentStorage> _logger;

    public LocalLeaveAttachmentStorage(
        IOptions<LeaveAttachmentOptions> options,
        ILogger<LocalLeaveAttachmentStorage> logger)
    {
        _root = Path.GetFullPath(options.Value.RootPath);
        _logger = logger;
    }

    public async Task<string> SaveAsync(Stream content, string fileName, CancellationToken ct)
    {
        // Foldered by month so the directory does not grow into one flat listing of everything
        // ever uploaded. The name is a fresh guid: the only part of the uploader's filename that
        // survives is the extension, and only from a fixed allow-list.
        var key = $"{DateTime.UtcNow:yyyy/MM}/{Guid.NewGuid():N}{SafeExtension(fileName)}";
        var path = ResolvePath(key);

        Directory.CreateDirectory(Path.GetDirectoryName(path)!);

        await using var file = File.Create(path);
        await content.CopyToAsync(file, ct);

        return key;
    }

    public Task<Stream?> OpenAsync(string storageKey, CancellationToken ct)
    {
        var path = ResolvePath(storageKey);
        return Task.FromResult<Stream?>(
            File.Exists(path) ? File.OpenRead(path) : null);
    }

    public Task DeleteAsync(string storageKey, CancellationToken ct)
    {
        try
        {
            var path = ResolvePath(storageKey);
            if (File.Exists(path))
            {
                File.Delete(path);
            }
        }
        catch (Exception ex)
        {
            // An orphaned file wastes disk; it does not break anything the caller was doing, and
            // the caller is already handling a failure of its own.
            _logger.LogWarning(ex, "Could not delete leave attachment {StorageKey}", storageKey);
        }

        return Task.CompletedTask;
    }

    /// <summary>
    /// Resolves a key under the root and refuses anything that climbs out of it. Keys are
    /// generated by <see cref="SaveAsync"/>, but they make a round trip through the database
    /// before coming back here, so this does not take their shape on trust.
    /// </summary>
    private string ResolvePath(string storageKey)
    {
        var full = Path.GetFullPath(Path.Combine(_root, storageKey));
        if (!full.StartsWith(_root + Path.DirectorySeparatorChar, StringComparison.Ordinal))
        {
            throw new InvalidOperationException($"Attachment key resolves outside the store: {storageKey}");
        }

        return full;
    }

    private static string SafeExtension(string fileName) =>
        Path.GetExtension(fileName).ToLowerInvariant() switch
        {
            ".pdf" => ".pdf",
            ".jpg" or ".jpeg" => ".jpg",
            ".png" => ".png",
            _ => string.Empty,
        };
}

public sealed class LeaveAttachmentOptions
{
    public const string SectionName = "LeaveAttachments";

    /// <summary>
    /// Folder the files live in, absolute or relative to the API's working directory. Outside
    /// wwwroot deliberately — these are medical documents and must only ever be served by the
    /// download endpoint, which checks who is asking, never by static file serving.
    /// </summary>
    public string RootPath { get; init; } = "App_Data/leave-attachments";
}
